# -*- coding: utf-8 -*-
"""E1E124025-Agus Hartono.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gyCT_vFHFmbDZ0qYCKsCQXGBmVv33WNE

Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from xgboost import XGBRegressor


url = 'https://raw.githubusercontent.com/tidyverse/ggplot2/main/data-raw/diamonds.csv'
df = pd.read_csv(url)

print("Dataset Berhasil Dimuat!")
print(f"Jumlah baris: {df.shape[0]}, Jumlah kolom: {df.shape[1]}")
df.head()

"""Load Dataset"""

# 1. Cek Missing Value & Duplikat
print("=== Pengecekan Data ===")
print(f"Missing Values:\n{df.isnull().sum().sum()}")
print(f"Jumlah Duplikat: {df.duplicated().sum()}")

# 2. Statistik Deskriptif
display(df.describe())

# 3. Visualisasi Distribusi Target (Price)

plt.figure(figsize=(10, 5))
sns.histplot(df['price'], kde=True, color='blue')
plt.title('Distribusi Harga Berlian (Target)')
plt.show()

# 4. Korelasi Antar Fitur Numerik
plt.figure(figsize=(10, 8))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Heatmap Korelasi Fitur Numerik')
plt.show()

# 5. Deteksi Outlier pada Fitur Utama (Carat)

plt.figure(figsize=(8, 4))
sns.boxplot(x=df['carat'], color='cyan')
plt.title('Deteksi Outlier pada Kolom Carat')
plt.show()

# Menghapus Duplikat
df = df.drop_duplicates()

# Definisi Urutan Kategori (Ordinal)
# Penting: Urutan harus benar agar model memahami 'Ideal' lebih baik dari 'Fair'
cut_categories = ['Fair', 'Good', 'Very Good', 'Premium', 'Ideal']
color_categories = ['J', 'I', 'H', 'G', 'F', 'E', 'D']
clarity_categories = ['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF']

numerical_features = ['carat', 'depth', 'table', 'x', 'y', 'z']
categorical_features = ['cut', 'color', 'clarity']

# ColumnTransformer: Scaling untuk angka, Ordinal Encoding untuk kategori
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OrdinalEncoder(categories=[cut_categories, color_categories, clarity_categories]), categorical_features)
    ])

print("Preprocessing Pipeline Berhasil Didefinisikan.")

X = df.drop('price', axis=1)
y = df['price']

# Skenario Split (10:90, 20:80, 30:70, 40:60)
test_sizes = [0.90, 0.80, 0.70, 0.60]
models = {
    'KNN': KNeighborsRegressor(n_neighbors=5, weights='distance'),
    'Random Forest': RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1),
    'XGBoost': XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=6, random_state=42)
}

full_results = []
best_r2 = -1
best_model_pipeline = None

for test_size in test_sizes:
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=42)
    scenario_label = f"{int((1-test_size)*100)}:{int(test_size*100)}"

    for name, model in models.items():
        # Buat Pipeline Lengkap
        pipeline = Pipeline(steps=[
            ('prep', preprocessor),
            ('reg', model)
        ])

        # Training
        pipeline.fit(X_train, y_train)

        # Prediksi & Evaluasi
        y_pred = pipeline.predict(X_test)
        r2 = r2_score(y_test, y_pred)
        rmse = np.sqrt(mean_squared_error(y_test, y_pred))
        mae = mean_absolute_error(y_test, y_pred)

        full_results.append({
            'Model': name,
            'Skenario (Train:Test)': scenario_label,
            'Akurasi (R2)': r2,
            'RMSE': rmse,
            'MAE': mae
        })

        if r2 > best_r2:
            best_r2 = r2
            best_model_pipeline = pipeline
            best_model_name = name

# Menampilkan Tabel Hasil
results_df = pd.DataFrame(full_results)
display(results_df.sort_values(by='Akurasi (R2)', ascending=False))

# 1. Bar Chart Akurasi
plt.figure(figsize=(12, 6))
sns.barplot(data=results_df, x='Skenario (Train:Test)', y='Akurasi (R2)', hue='Model')
plt.title('Perbandingan Akurasi (R2) antar Model dan Skenario Split')
plt.ylim(0.90, 1.0)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

# 2. Feature Importance Model Terbaik
if best_model_name in ['Random Forest', 'XGBoost']:
    importances = best_model_pipeline.named_steps['reg'].feature_importances_
    all_features = numerical_features + categorical_features
    plt.figure(figsize=(10, 5))
    pd.Series(importances, index=all_features).sort_values().plot(kind='barh', color='salmon')
    plt.title(f'Fitur Paling Berpengaruh - {best_model_name}')
    plt.show()

# 3. Simpan Model untuk Streamlit
joblib.dump(best_model_pipeline, 'model_diamonds_final.pkl')
print(f"\nModel terbaik ({best_model_name}) telah disimpan dengan nama 'model_diamonds_final.pkl'")